version: '3'

services:
  keycloak:
    image: jboss/keycloak
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=f00b@rIt
    - PROXY_ADDRESS_FORWARDING=true
    volumes:
    - ./dev-env/logs:/opt/jboss/keycloak/standalone/log
    - ./dev-env/keycloak-data:/opt/jboss/keycloak/standalone/data

  nginx:
    image: nginx
    volumes:
    - ./dev-env/nginx.conf:/etc/nginx/nginx.conf
    - ./dev-env/logs:/var/log
    links:
    - keycloak
volumes:
  mongodata: {}
