version: '3'

services:
  keycloak:
    image: jboss/keycloak
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=f00b@rIt
    - PROXY_ADDRESS_FORWARDING=true
    volumes:
    - ./dev-env/logs:/opt/jboss/keycloak/standalone/log
    - ./dev-env/data/keycloak:/opt/jboss/keycloak/standalone/data

  gradle_build:
    image: frekele/gradle:3.5-jdk8
    volumes:
    - .:/project
    working_dir: /project
    command: "gradle run"
    links:
    - keycloak


  nginx:
    image: nginx
    volumes:
    - ./dev-env/nginx.conf:/etc/nginx/nginx.conf
    - ./dev-env/logs:/var/log
    ports:
      - 8080:8080
    links:
    - keycloak
    - gradle_build
volumes:
  mongodata: {}
